### PR TITLE
Add 24768, 21200, 13617, 24296, 12351, 12352, 20268, 9698, 22421, 18813, 17042, 24312 ez_code

### PR DESCRIPTION
**Pull request by w8385**
- [x] Did you stage index file?
- [x] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [x] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

### CODE REVIEW

**Comment by w8385** [comment]
# 24768
image

**Comment by w8385** [comment]
# 21200
image

**Comment by w8385** [comment]
# 13617
image

**Comment by w8385** [comment]
# 24296
image

**Comment by w8385** [comment]
# 12352
image

**Comment by w8385** [comment]
# 20268
image

**Comment by w8385** [comment]
# 9698
image

**Comment by w8385** [comment]
# 22421
image

**Comment by w8385** [comment]
# 18813
image

**Comment by w8385** [comment]
# 17042
image

**Comment by w8385** [comment]
# 24312
image

**Review by kiwiyou — APPROVED** [review]
번역 감사합니다!

**Pull request merged**
