### PR TITLE
Add 5292, 5343, 25840, 24310, 25869, 26314 w8385

### PR DESCRIPTION
**Pull request by w8385**
- [x] Did you stage index file?
- [x] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [x] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

### CODE REVIEW

**Comment by w8385** [comment]
# 5292
image

**Comment by w8385** [comment]
# 5343
image

**Comment by w8385** [comment]
# 25840
image

**Comment by w8385** [comment]
# 24310
image

**Comment by w8385** [comment]
# 25869
image

**Comment by w8385** [comment]
# 26314
image

**Review by kiwiyou — APPROVED** [review]
번역 감사합니다!

**Pull request merged**
