### PR TITLE
Add 6784, 22380, 26026, 26741, 27329, 26940

### PR DESCRIPTION
**Pull request by w8385**
# 6784
image

### CODE REVIEW

**Comment by w8385** [comment]
image

**Comment by w8385** [comment]
image

**Comment by w8385** [comment]
# 26741
image

**Comment by w8385** [comment]
# 24198
image

**Comment by w8385** [comment]
# 27329
image

**Comment by w8385** [comment]
# 26940
image

**Review by kiwiyou — APPROVED** [review]
번역 감사합니다!

**Pull request merged**
