### PR TITLE
Add 4758, 4422, 4425, 3512 w8385

### PR DESCRIPTION
**Pull request by w8385**
- [x] Did you stage index file?
- [x] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [x] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

### CODE REVIEW

**Comment by w8385** [comment]
# 4758

image

**Comment by w8385** [comment]
# 4422
image

**Comment by w8385** [comment]
# 4425
image

**Comment by w8385** [comment]
# 3512
image

**Review by kiwiyou — APPROVED** [review]
번역 감사합니다!

**Pull request merged**
