### PR TITLE
Add 9443, 21167, 22388, 23397 ez_code

### PR DESCRIPTION
**Pull request by w8385**
- [x] Did you stage index file?
- [x] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [x] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

### CODE REVIEW

**Comment by w8385** [comment]
# 9443
image

**Comment by w8385** [comment]
# 21167
image

**Comment by w8385** [comment]
# 22388
image

**Comment by w8385** [comment]
# 23397
image

**Comment by w8385** [comment]
# 4850
image

**Review by kiwiyou — APPROVED** [review]
번역 감사합니다!

**Pull request merged**
