### PR TITLE
Add 15151, 11368, 9161, 14683, 7947, 8574, 20360, 13063, 8661, 20674, 10695 ez_code

### PR DESCRIPTION
**Pull request by w8385**
- [x] Did you stage index file?
- [x] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [x] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

### CODE REVIEW

**Comment by w8385** [comment]
# 11368
image

**Comment by w8385** [comment]
# 9161
image

**Comment by w8385** [comment]
# 14683
힌트는 제가 번역했습니다 ><

image
image

**Comment by w8385** [comment]
# 7947
image

**Comment by w8385** [comment]
# 21645
image

**Comment by w8385** [comment]
# 8574
image

**Comment by w8385** [comment]
# 20360
image

**Comment by w8385** [comment]
# 13063
image

**Comment by w8385** [comment]
# 8661
image

**Comment by w8385** [comment]
# 20674
image

**Comment by w8385** [comment]
# 10695
image

**Review by kiwiyou — APPROVED** [review]
번역 감사합니다!

**Pull request merged**
