### PR TITLE
Add 20214, 18063, 25841, 8721, 9907, 21146 w8385

### PR DESCRIPTION
**Pull request by w8385**
- [x] Did you stage index file?
- [x] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [x] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

### CODE REVIEW

**Comment by w8385** [comment]
# 20214
image

**Comment by w8385** [comment]
# 18063
image

**Comment by w8385** [comment]
# 8721
image

**Comment by w8385** [comment]
# 9907
image

**Comment by w8385** [comment]
# 21146
image

**Review by kiwiyou — APPROVED** [review]
번익 감사합니다!

**Pull request merged**
