### PR TITLE
Add 24606, 25278, 24830, 24609 ez_code

### PR DESCRIPTION
**Pull request by w8385**
- [x] Did you stage index file?
- [x] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [x] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

### CODE REVIEW

**Comment by w8385** [comment]
# 24606
수식 부분 표기가 묘한데, 원문을 그대로 옮겨 적었습니다.

image

**Comment by w8385** [comment]
# 25278
image

**Comment by w8385** [comment]
# 24830
image

**Review by kiwiyou — APPROVED** [review]
번역 감사합니다!

**Pull request merged**
