### PR TITLE
Add 9317, 17783, 9664, 13363, 13773, 15279, 8815, 14013

### PR DESCRIPTION
**Pull request by w8385**
- [x] Did you stage index file?
- [x] Did you follow [README.md](https://github.com/kiwiyou/boj-user-translation/blob/main/README.md)?
- [x] Did you follow [formatting guide](https://github.com/kiwiyou/boj-user-translation/blob/main/formatting.md)?

### CODE REVIEW

**Comment by w8385** [comment]
# 9317
image

**Comment by w8385** [comment]
# 17783
image

**Comment by w8385** [comment]
# 9317
image

**Comment by w8385** [comment]
# 13363
image

**Comment by w8385** [comment]
# 13363
image

**Comment by w8385** [comment]
# 15279
image

**Comment by w8385** [comment]
# 8815
image

**Comment by w8385** [comment]
# 14013
image

**Review by kiwiyou — APPROVED** [review]
번역 감사합니다!

**Pull request merged**
